Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sig0_dc = (
    post_process_eodc_cube(sig0_dc, items_sig0, bands)
    .rename_vars({"VV": "sig0"})
    .assign_coords(orbit=("time", extract_orbit_names(items_sig0)))
    .dropna(dim="time", how="all")
    .sortby("time")
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mCPLE_HttpResponseError[0m                    Traceback (most recent call last)
File [0;32mrasterio/_base.pyx:310[0m, in [0;36mrasterio._base.DatasetBase.__init__[0;34m()[0m

File [0;32mrasterio/_base.pyx:221[0m, in [0;36mrasterio._base.open_dataset[0;34m()[0m

File [0;32mrasterio/_err.pyx:359[0m, in [0;36mrasterio._err.exc_wrap_pointer[0;34m()[0m

[0;31mCPLE_HttpResponseError[0m: HTTP response code: 403

During handling of the above exception, another exception occurred:

[0;31mRasterioIOError[0m                           Traceback (most recent call last)
Cell [0;32mIn[11], line 2[0m
[1;32m      1[0m sig0_dc [38;5;241m=[39m (
[0;32m----> 2[0m     [43mpost_process_eodc_cube[49m[43m([49m[43msig0_dc[49m[43m,[49m[43m [49m[43mitems_sig0[49m[43m,[49m[43m [49m[43mbands[49m[43m)[49m
[1;32m      3[0m [43m    [49m[38;5;241;43m.[39;49m[43mrename_vars[49m[43m([49m[43m{[49m[38;5;124;43m"[39;49m[38;5;124;43mVV[39;49m[38;5;124;43m"[39;49m[43m:[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43msig0[39;49m[38;5;124;43m"[39;49m[43m}[49m[43m)[49m
[1;32m      4[0m [43m    [49m[38;5;241;43m.[39;49m[43massign_coords[49m[43m([49m[43morbit[49m[38;5;241;43m=[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mtime[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mextract_orbit_names[49m[43m([49m[43mitems_sig0[49m[43m)[49m[43m)[49m[43m)[49m
[1;32m      5[0m [43m    [49m[38;5;241;43m.[39;49m[43mdropna[49m[43m([49m[43mdim[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mtime[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mhow[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mall[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      6[0m     [38;5;241m.[39msortby([38;5;124m"[39m[38;5;124mtime[39m[38;5;124m"[39m)
[1;32m      7[0m )

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/xarray/core/dataset.py:6605[0m, in [0;36mDataset.dropna[0;34m(self, dim, how, thresh, subset)[0m
[1;32m   6603[0m     [38;5;28;01mif[39;00m dim [38;5;129;01min[39;00m array[38;5;241m.[39mdims:
[1;32m   6604[0m         dims [38;5;241m=[39m [d [38;5;28;01mfor[39;00m d [38;5;129;01min[39;00m array[38;5;241m.[39mdims [38;5;28;01mif[39;00m d [38;5;241m!=[39m dim]
[0;32m-> 6605[0m         count [38;5;241m+[39m[38;5;241m=[39m [43mto_numpy[49m[43m([49m[43marray[49m[38;5;241;43m.[39;49m[43mcount[49m[43m([49m[43mdims[49m[43m)[49m[38;5;241;43m.[39;49m[43mdata[49m[43m)[49m
[1;32m   6606[0m         size [38;5;241m+[39m[38;5;241m=[39m math[38;5;241m.[39mprod([[38;5;28mself[39m[38;5;241m.[39msizes[d] [38;5;28;01mfor[39;00m d [38;5;129;01min[39;00m dims])
[1;32m   6608[0m [38;5;28;01mif[39;00m thresh [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/xarray/namedarray/pycompat.py:111[0m, in [0;36mto_numpy[0;34m(data, **kwargs)[0m
[1;32m    109[0m [38;5;28;01mif[39;00m is_chunked_array(data):
[1;32m    110[0m     chunkmanager [38;5;241m=[39m get_chunked_array_type(data)
[0;32m--> 111[0m     data, [38;5;241m*[39m_ [38;5;241m=[39m [43mchunkmanager[49m[38;5;241;43m.[39;49m[43mcompute[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    112[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(data, array_type([38;5;124m"[39m[38;5;124mcupy[39m[38;5;124m"[39m)):
[1;32m    113[0m     data [38;5;241m=[39m data[38;5;241m.[39mget()

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/xarray/namedarray/daskmanager.py:85[0m, in [0;36mDaskManager.compute[0;34m(self, *data, **kwargs)[0m
[1;32m     80[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mcompute[39m(
[1;32m     81[0m     [38;5;28mself[39m, [38;5;241m*[39mdata: Any, [38;5;241m*[39m[38;5;241m*[39mkwargs: Any
[1;32m     82[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mtuple[39m[np[38;5;241m.[39mndarray[Any, _DType_co], [38;5;241m.[39m[38;5;241m.[39m[38;5;241m.[39m]:
[1;32m     83[0m     [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mdask[39;00m[38;5;21;01m.[39;00m[38;5;21;01marray[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m compute
[0;32m---> 85[0m     [38;5;28;01mreturn[39;00m [43mcompute[49m[43m([49m[38;5;241;43m*[39;49m[43mdata[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/dask/base.py:661[0m, in [0;36mcompute[0;34m(traverse, optimize_graph, scheduler, get, *args, **kwargs)[0m
[1;32m    658[0m     postcomputes[38;5;241m.[39mappend(x[38;5;241m.[39m__dask_postcompute__())
[1;32m    660[0m [38;5;28;01mwith[39;00m shorten_traceback():
[0;32m--> 661[0m     results [38;5;241m=[39m [43mschedule[49m[43m([49m[43mdsk[49m[43m,[49m[43m [49m[43mkeys[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    663[0m [38;5;28;01mreturn[39;00m repack([f(r, [38;5;241m*[39ma) [38;5;28;01mfor[39;00m r, (f, a) [38;5;129;01min[39;00m [38;5;28mzip[39m(results, postcomputes)])

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/odc/loader/_builder.py:435[0m, in [0;36m_dask_loader_tyx[0;34m()[0m
[1;32m    433[0m [38;5;28;01mwith[39;00m rdr[38;5;241m.[39mrestore_env(env, load_state):
[1;32m    434[0m     [38;5;28;01mfor[39;00m ti, ti_srcs [38;5;129;01min[39;00m [38;5;28menumerate[39m(srcs):
[0;32m--> 435[0m         _fill_nd_slice(
[1;32m    436[0m             ti_srcs, gbox, cfg, chunk[ti], ydim[38;5;241m=[39mydim, selection[38;5;241m=[39mselection
[1;32m    437[0m         )
[1;32m    438[0m     [38;5;28;01mreturn[39;00m chunk

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/odc/loader/_builder.py:512[0m, in [0;36m_fill_nd_slice[0;34m()[0m
[1;32m    509[0m     [38;5;28;01mreturn[39;00m dst
[1;32m    511[0m src, [38;5;241m*[39mrest [38;5;241m=[39m srcs
[0;32m--> 512[0m yx_roi, pix [38;5;241m=[39m src[38;5;241m.[39mread(cfg, dst_gbox, dst[38;5;241m=[39mdst, selection[38;5;241m=[39mselection)
[1;32m    513[0m [38;5;28;01massert[39;00m [38;5;28mlen[39m(yx_roi) [38;5;241m==[39m [38;5;241m2[39m
[1;32m    514[0m [38;5;28;01massert[39;00m pix[38;5;241m.[39mndim [38;5;241m==[39m dst[38;5;241m.[39mndim

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/odc/loader/_rio.py:115[0m, in [0;36mread[0;34m()[0m
[1;32m    107[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mread[39m(
[1;32m    108[0m     [38;5;28mself[39m,
[1;32m    109[0m     cfg: RasterLoadParams,
[0;32m   (...)[0m
[1;32m    113[0m     selection: Optional[ReaderSubsetSelection] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m    114[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mtuple[39m[[38;5;28mtuple[39m[[38;5;28mslice[39m, [38;5;28mslice[39m], np[38;5;241m.[39mndarray]:
[0;32m--> 115[0m     [38;5;28;01mreturn[39;00m rio_read([38;5;28mself[39m[38;5;241m.[39m_src, cfg, dst_geobox, dst[38;5;241m=[39mdst, selection[38;5;241m=[39mselection)

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/odc/loader/_rio.py:526[0m, in [0;36mrio_read[0;34m()[0m
[1;32m    520[0m     [38;5;28;01mif[39;00m cfg[38;5;241m.[39mfail_on_error:
[1;32m    521[0m         log[38;5;241m.[39merror(
[1;32m    522[0m             [38;5;124m"[39m[38;5;124mAborting load due to failure while reading: [39m[38;5;132;01m%s[39;00m[38;5;124m:[39m[38;5;132;01m%d[39;00m[38;5;124m"[39m,
[1;32m    523[0m             src[38;5;241m.[39muri,
[1;32m    524[0m             src[38;5;241m.[39mband,
[1;32m    525[0m         )
[0;32m--> 526[0m         [38;5;28;01mraise[39;00m e
[1;32m    527[0m [38;5;28;01mexcept[39;00m rasterio[38;5;241m.[39merrors[38;5;241m.[39mRasterioError [38;5;28;01mas[39;00m e:
[1;32m    528[0m     [38;5;28;01mif[39;00m cfg[38;5;241m.[39mfail_on_error:

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/odc/loader/_rio.py:512[0m, in [0;36mrio_read[0;34m()[0m
[1;32m    508[0m     [38;5;28;01mreturn[39;00m roi, out[38;5;241m.[39mtranspose([[38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m0[39m])
[1;32m    510[0m [38;5;28;01mtry[39;00m:
[1;32m    511[0m     [38;5;28;01mreturn[39;00m fixup_out(
[0;32m--> 512[0m         _rio_read(src, cfg, dst_geobox, prep_dst(dst), selection[38;5;241m=[39mselection)
[1;32m    513[0m     )
[1;32m    514[0m [38;5;28;01mexcept[39;00m (
[1;32m    515[0m     rasterio[38;5;241m.[39merrors[38;5;241m.[39mRasterioIOError,
[1;32m    516[0m     rasterio[38;5;241m.[39merrors[38;5;241m.[39mRasterBlockError,
[1;32m    517[0m     rasterio[38;5;241m.[39merrors[38;5;241m.[39mWarpOperationError,
[1;32m    518[0m     rasterio[38;5;241m.[39merrors[38;5;241m.[39mWindowEvaluationError,
[1;32m    519[0m ) [38;5;28;01mas[39;00m e:
[1;32m    520[0m     [38;5;28;01mif[39;00m cfg[38;5;241m.[39mfail_on_error:

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/odc/loader/_rio.py:560[0m, in [0;36m_rio_read[0;34m()[0m
[1;32m    549[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_rio_read[39m(
[1;32m    550[0m     src: RasterSource,
[1;32m    551[0m     cfg: RasterLoadParams,
[0;32m   (...)[0m
[1;32m    556[0m     [38;5;66;03m# if resampling is `nearest` then ignore sub-pixel translation when deciding[39;00m
[1;32m    557[0m     [38;5;66;03m# whether we can just paste source into destination[39;00m
[1;32m    558[0m     ttol [38;5;241m=[39m [38;5;241m0.9[39m [38;5;28;01mif[39;00m cfg[38;5;241m.[39mnearest [38;5;28;01melse[39;00m [38;5;241m0.05[39m
[0;32m--> 560[0m     [38;5;28;01mwith[39;00m rasterio[38;5;241m.[39mopen(src[38;5;241m.[39muri, [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m, sharing[38;5;241m=[39m[38;5;28;01mFalse[39;00m) [38;5;28;01mas[39;00m rdr:
[1;32m    561[0m         [38;5;28;01massert[39;00m [38;5;28misinstance[39m(rdr, rasterio[38;5;241m.[39mDatasetReader)
[1;32m    562[0m         ovr_idx: Optional[[38;5;28mint[39m] [38;5;241m=[39m [38;5;28;01mNone[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/rasterio/env.py:463[0m, in [0;36mwrapper[0;34m()[0m
[1;32m    460[0m     session [38;5;241m=[39m DummySession()
[1;32m    462[0m [38;5;28;01mwith[39;00m env_ctor(session[38;5;241m=[39msession):
[0;32m--> 463[0m     [38;5;28;01mreturn[39;00m f([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [0;32m/opt/hostedtoolcache/Python/3.10.17/x64/lib/python3.10/site-packages/rasterio/__init__.py:356[0m, in [0;36mopen[0;34m()[0m
[1;32m    353[0m     path [38;5;241m=[39m _parse_path(raw_dataset_path)
[1;32m    355[0m [38;5;28;01mif[39;00m mode [38;5;241m==[39m [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m:
[0;32m--> 356[0m     dataset [38;5;241m=[39m DatasetReader(path, driver[38;5;241m=[39mdriver, sharing[38;5;241m=[39msharing, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    357[0m [38;5;28;01melif[39;00m mode [38;5;241m==[39m [38;5;124m"[39m[38;5;124mr+[39m[38;5;124m"[39m:
[1;32m    358[0m     dataset [38;5;241m=[39m get_writer_for_path(path, driver[38;5;241m=[39mdriver)(
[1;32m    359[0m         path, mode, driver[38;5;241m=[39mdriver, sharing[38;5;241m=[39msharing, [38;5;241m*[39m[38;5;241m*[39mkwargs
[1;32m    360[0m     )

File [0;32mrasterio/_base.pyx:312[0m, in [0;36mrasterio._base.DatasetBase.__init__[0;34m()[0m

[0;31mRasterioIOError[0m: HTTP response code: 403

